### ISSUE TITLE
Enhancement Ideas

### ISSUE THREAD

**Issue by rswafford** [gotdibbs/WebResourceManager#2]
After using this in daily workflow for a couple of days on a larger codebase, a couple things that might be nice to have in the UI:

- Server and Local Modified dates both, possibly with a highlight or additional status of "Locally modified" if local is newer, or "Server modified" if server is newer.
- Tree-view for folders, or a way to filter the view down to a particular sub-folder

I may try and tackle the modified dates one on my fork, if time allows. Thoughts? Are either of these on your radar already?

**Comment by gotdibbs** [comment]
Good points for sure, glad it's being a help overall! I've thought about those before and here's my general thoughts on each:

- local and remote modified are always going to be different, so I'd be curious to hear more of your thoughts on the use case here...is it just identifying if a local resource has yet to be uploaded? Because that should be tracked in the status column. I also didn't want to trust the file system dates, so I'm leaning more heavily on things changing after the app opens/row versions/ and manual diffs to validate status.
- I really hate the tree view that XrmToolbox has and have tried to stay away from that/find what the real use cases are for filtering and add those as views. That said, it's entirely possible I'm missing a use case, or that there's a better way to do folders. My thought was that if you have complex folder structures, like a set of react apps, that you can create multiple profiles for each sub-root and adjust the default namespace to match the actual folder structure. Thus why it ignores child folders with their own gitignore/package.json. Beyond that there's views to filter down to only those changes that have yet to be uploaded, etc.

In general the list is there to be a reference of what's where when hopping on a project, but the intent is that in RL you have that filtered down automatically so you're not having to hunt through things to find what you're looking for. Maybe pinning a view would be helpful? Example: my workflow is open app, start tracking, switch to filtered view if it's a large project, start editing in VS code, tab back and upload. Beyond that, the app should let you know when there's been a remote change only when needed, vs you having to scroll through the list to find that out. More like us being notified only when necessary by the app, rather than us polling the app looking for stuff. Thoughts?

**Comment by rswafford** [comment]
- Local/remote modified: mainly for tracking that "hey, this local file has changed and you haven't uploaded your changes yet".  Maybe a way to trigger diffs of selected rows, or something? My current use case is updating a large number of script files, and not always uploading them as soon as one file's edits are done. After re-reading your full comment, I just discovered the Watching/Changed status -- *that* is what I was missing for this case.

- Agreed on XrmToolbox's tree view - I don't really care for quite how they have it laid out. For root namespaces, is the idea that a whole namespace/folder path would be handled as a "root namespace" potentially -- a la "pre_/SomeApp/Scripts/Forms" as a profile's namespace?

**Comment by gotdibbs** [comment]
So the root namespace is determined relative to the directory you choose when setting up the profile. What you set for the namespace in the profile just gets prepended.

Example: root directory is `c:\project\dashboard\dist` and namespace is set to `proj_/dashboard`, then `proj_/dashboard/index.html` would map to `c:\project\dashboard\dist\index.html`
